#!/bin/bash
#
# (c) Matteo Corti, ETH Zurich, 2007
#
# check_ssl_cert
#
# Checks an X.509 certificate:
# - checks if the server is running and delivers a valid certificate
# - checks if the CA matches a given pattern
# - checks the validity

VERSION=1.1.0

################################################################################
# Functions

################################################################################
# Prints usage information
# Params
#   $1 error message (optional)
usage() {

    if [ -n "$1" ] ; then
        echo "Error: $1" 1>&2
    fi
    
    echo
    echo "Usage: check_ssl_cert -H server [-hvw?] [-p port]"
    echo
    echo "   -d days    minimum number of days a certificate has to be valid"
    echo "   -e address pattern to match the email address contained in the certificate"
    echo "   -h, -?     this help message"
    echo "   -H host    server"
    echo "   -i issuer  pattern to match the issuer of the certificate"
    echo "   -o org     pattern to match the organization of the certificate"
    echo "   -p port    TCP port"
    echo "   -v         verbose output"
    echo "   -V         version"
    echo
    echo "Report bugs to: Matteo Corti <matteo.corti@id.ethz.ch>"
    echo

    exit 3

}

cleanup() {

    if [ -f $CERT  ] ; then rm $CERT;  fi
    if [ -f $ERROR ] ; then rm $ERROR; fi

}

################################################################################
# Exits with a critical message
# Params
#   $1 error message
critical() {
    echo "SSL CERT CRITICAL - $1"
    cleanup;
    exit 2
}

################################################################################
# Exits with a warning message
# Param
#   $1 warning message
warning() {
    echo "SSL CERT WARN - $1"
    cleanup;
    exit 1
}

################################################################################
# Formats a time in seconds using days minutes and seconds
# Params
#   $1 time in seconds
format_days() {

    SECONDS=$1

    if [ $((SECONDS/86400)) -gt 0 ] ; then
        STR="$((SECONDS/86400)) days"
        SECONDS=$((SECONDS-(SECONDS/86400)*86400))
    fi

    if [ $((SECONDS/3600)) -gt 0 ] ; then
        STR="$STR $((SECONDS/3600)) hours"
        SECONDS=$((SECONDS-(SECONDS/3600)*3600))
    fi

    if [ $((SECONDS/60)) -gt 0 ] ; then
        STR="$STR $((SECONDS/60)) minutes"
        SECONDS=$((SECONDS-(SECONDS/60)*60))
    fi

    STR="$STR ${SECONDS} seconds"

    echo $STR
        
}

################################################################################
# Checks if a given program is available and executable
# Params
#   $1 program name
check_prog() {

    PROG=`which $1`

    if [ -z "$PROG" ] ; then
        critical "cannot find $1"
    fi

    if [ ! -x "$PROG" ] ; then
        critical "$PROG is not executable"
    fi

}

################################################################################
# Main
################################################################################

# process command line options
PORT=443
while getopts "vh?H:Vp:d:i:o:e:" opt; do
    case $opt in
        d )      DAYS=$OPTARG;        ;;
        e )      ADDR=$OPTARG;        ;;
        h | \? ) usage ; exit 3;      ;;
        i )      ISSUER=$OPTARG;      ;;
        o )      ORGANIZATION=$OPTARG ;;
        v )      VERBOSE=1;           ;;
        V )      echo "check_ssl_cert version ${VERSION}"; exit 3; ;;
        H )      HOST=$OPTARG;        ;;
        p )      PORT=$OPTARG;        ;;
    esac
done
shift $(($OPTIND - 1))

################################################################################
# sanity checks

###############
# Check options
if [ -z "${HOST}" ] ; then
    usage "No host specified"
fi

#######################
# Check needed programs

check_prog openssl
OPENSSL=$PROG

################################################################################
# fetch the X.509 certificate

CERT="/tmp/check_certs-out.$$"
ERROR="/tmp/check_certs-errors.$$"

echo 'Q' | $OPENSSL s_client -connect $HOST:$PORT 2> ${ERROR} 1> ${CERT}

if grep -q "Connection refused" ${ERROR} ; then
    rm -f ${CERT} ${ERROR}
    critical "connection refused ($HOST:$PORT)"
    return
fi

################################################################################
# parse the X.509 certificate

CA=`$OPENSSL x509 -in ${CERT} -issuer -noout | sed -e "s/.*\/O=//" | sed -r "s/\/[A-Z]+=.*//"`
DATE=`$OPENSSL x509 -in ${CERT} -enddate -noout | sed "s/notAfter\=//"`

################################################################################
# check the issuer

if [ -n "$ISSUER" ] ; then
    if ! echo $CA | grep -q "^$ISSUER$" ; then
        critical "invalid CA ($ISSUER does not match $CA)"
    fi
fi

################################################################################
# check the validity

if [ -n "$DAYS" ] ; then

    if ! echo $DAYS | grep -q [1-9][0-9]* ; then
        critical "invalid number of days ($DAYS)"
    fi

    DIFF=$((`date -d "$DATE" "+%s"` - `date "+%s"`))
    DAYS=$((DAYS * 86400))

    if [ $DIFF -le 0 ] ; then
        critical "certificate is expired (was valid until $DATE)"
    fi

    if [ $DIFF -le $DAYS ] ; then
        MESSAGE=`format_days $DIFF`
        MESSAGE=`echo "certificate is exipring in" $MESSAGE`
        warning "$MESSAGE"
    fi
      
fi

################################################################################
# check the organization

if [ -n "$ORGANIZATION" ] ; then

    ORG=`$OPENSSL x509 -in ${CERT} -subject -noout | sed -e "s/.*\/O=//" | sed -e "s/\/.*//"`

    if ! echo $ORG | grep -q "^$ORGANIZATION" ; then
        critical "invalid organization ($ORGANIZATION does not match $ORG)"
    fi

fi

################################################################################
# check the organization

if [ -n "$ADDR" ] ; then

    EMAIL=`$OPENSSL x509 -in ${CERT} -email -noout`

    if ! echo $EMAIL | grep -q "^$ADDR" ; then
        critical "invalid email ($ADDR does not match $EMAIL)"
    fi

fi

################################################################################
# clean up
rm -f ${CERT} ${ERROR}

echo "SSL CERT OK - X.509 certificate from $CA valid until $DATE"

cleanup;

exit 0
