name: Unit tests with proxy

on:
  push:
    branches:
      - $default-branch
      - development
      - master
    paths-ignore:
      - varia/**
      - check_ssl_cert.1
      - '**.md'
      - utils/prepare_rpm.sh
      - .github/workflows/publish.yml
  # Run tests for any PRs
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:

  ##############################################################################
  # macOS

  macos:
    name: Running unit tests on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:

      - name: Git clone repository
        uses: actions/checkout@v4

      - name: Install shellcheck
        run: brew install shellcheck shunit2 bash-completion nmap tinyproxy

      - name: install cpanm and Date::Parse
        uses: perl-actions/install-with-cpanm@stable
        with:
          install: Date::Parse

      - name: Run the unit tests
        run:  |
          uname -a \
          && make unit_tests_with_proxy \
          && bash -c "source ./check_ssl_cert.completion && complete -p check_ssl_cert" \
          && make dist \
          && sudo make install_bash_completion && bash -c "source ./check_ssl_cert.completion && complete -p check_ssl_cert" \
          && if command -v shellcheck > /dev/null 2>&1  ; then shellcheck ./check_ssl_cert test/*.sh ; fi

  rpm:
    # The host should always be linux
    runs-on: ubuntu-latest
    name: Running RPM tests on ${{ matrix.distro }}
    strategy:
      fail-fast: false
      matrix:
        distro:
          - 'fedora:latest'
        include:
          - distro: 'fedora:latest'
            pre: >-
              dnf install -y hostname &&
              dnf install -y nmap ShellCheck curl sudo perl make bzip2 file openssl bind-utils rpm-build git bash-completion
    steps:

      - name: Git clone repository
        uses: actions/checkout@v4

      - name: Build the RPM on ${{ matrix.distro }}
        env:
          PRE: ${{ matrix.pre }}
        run: |
          echo $PRE > ./prep-cmd.sh
          docker run --network host -w /check_ssl_cert -v ${PWD}:/check_ssl_cert ${{ matrix.distro }} \
              /bin/sh -c 'sh ./prep-cmd.sh \
              && uname -a \
              && make rpm'

  rpm-nocompletion:
    # The host should always be linux
    runs-on: ubuntu-latest
    name: Running RPM tests without bash completion on ${{ matrix.distro }}
    strategy:
      fail-fast: false
      matrix:
        distro:
          - 'fedora:latest'
        include:
          - distro: 'fedora:latest'
            pre: >-
              dnf install -y hostname &&
              dnf install -y nmap ShellCheck curl sudo perl make bzip2 file openssl bind-utils rpm-build git
    steps:

      - name: Git clone repository
        uses: actions/checkout@v4

      - name: Build the RPM on ${{ matrix.distro }}
        env:
          PRE: ${{ matrix.pre }}
        run: |
          echo $PRE > ./prep-cmd.sh
          docker run --network host -w /check_ssl_cert -v ${PWD}:/check_ssl_cert ${{ matrix.distro }} \
              /bin/sh -c 'sh ./prep-cmd.sh \
              && uname -a \
              && make rpm'
